### ISSUE TITLE
Mettre le nouveau logo (Nguyen Tay en manuscrit)

### ISSUE THREAD

**Issue by nguyentay** [nguyentay/nguyentay.art#2]
Mettre le nouveau logo (Nguyen Tay en manuscrit) 
![png logo nguyen-03](https://user-images.githubusercontent.com/31181773/29494690-0103e718-85b0-11e7-8eb3-fcb3891c598e.png)

**Comment by sunix** [comment]
@nguyentay tu peux me dire si ca te va le logo ? si c'est ok je l'applique sur toutes les pages

http://nguyentay.art/home.html

**Comment by nguyentay** [comment]
Oui mais tu peux justifier en mettant au même niveau que les sous-catégorie.
