### ISSUE TITLE
Changer les logo "réseaux sociaux" et faire le recréer avec le compte Instagram 

### ISSUE THREAD

**Issue by nguyentay** [nguyentay/nguyentay.art#21]
![Unknown](https://user-images.githubusercontent.com/31181773/79066644-cab6e800-7cb9-11ea-85fb-e32eb507d4c8.jpeg)

**Comment by nguyentay** [comment]
Instagram @nguyentay.art

**Comment by sunix** [comment]
les logos, tu les as en svg ?
