### ISSUE TITLE
Changer page contact 

### ISSUE THREAD

**Issue by nguyentay** [nguyentay/nguyentay.art#7]
supprimer le formulaire contact et remplacer par lien email nguyentayartist@gmail.com

**Comment by sunix** [comment]
@nguyentay dis moi si ca te va
http://nguyentay.art/contact.html

**Comment by nguyentay** [comment]
Il faut enlever le logo, le nom et l'adresse de Galerie Beauté du matin calme 
Enlever mon email et les numéros de téléphones
